### ISSUE TITLE
An error occured while executing doInBackground()

### ISSUE THREAD

**Issue by it9xpro** [DmitryMalkovich/popular-movies-app#2]
i am new member help me fix 
: An error occured while executing doInBackground()
 at com.dmitrymalkovich.android.popularmoviesapp.FetchMoviesTask.doInBackground(FetchMoviesTask.java:127)
                                                                                                at com.dmitrymalkovich.android.popularmoviesapp.FetchMoviesTask.doInBackground(FetchMoviesTask.java:39)

**Comment by DmitryMalkovich** [comment]
Hello @it9xpro, do you set API_KEY for TMDb API here: https://github.com/DmitryMalkovich/popular-movies-app/blob/master/gradle.properties?

If it your case, sorry. I had to describe it in README.

**You can create your own one very easy!** Here: https://www.themoviedb.org/account/signup?language=en-EN

"If you're submitting via a public Github repository, please make sure any external API key that you utilize, has been removed from your code. It's highly unsafe (and often breaks the Terms of Service) to include API keys in public repos, so you need to remove yours.

**Comment by DmitryMalkovich** [comment]
I updated the README and changed release bug apk. Thank you @it9xpro!
