### ISSUE TITLE
Api link don't understand and add new feature.

### ISSUE THREAD

**Issue by paveltech** [DmitryMalkovich/popular-movies-app#3]
I was looking your code and i am trying to understand where you place your api link?? i just found something in MovieDatabaseService.java class but i don't understand it properly.
I want to add up-comming movie list into apps.
Where and how i can add this option??
Thanks for such awesome Application.

**Comment by DmitryMalkovich** [comment]
Hello @paveltech,

 "App uses The Movie Database API. You have to enter your API key in order to run the app. You can create your own one very easy! https://www.themoviedb.org/account/signup?language=en-EN. When you get it, just set it here: "popular-movies-app/gradle.properties"

For example: TheMovieDatabasepApiKey="YOUR OWN API KEY". Unfortunately it is not allowed to share your api key here.

**Comment by DmitryMalkovich** [comment]
Looking forward for your pull-request ;)

**Comment by paveltech** [comment]
Hi, Thanks for your reply finally i can implement it into my application but there i faced another problem when i make a HTTP request i only get 20 movie list that means only page:1 How i can get page:2 movie list?

**Comment by DmitryMalkovich** [comment]
@paveltech What call to TMDB api did you used?

**Comment by paveltech** [comment]
I show your code and i think your code is pretty cool then i decided to use your code using retrofit.
But when i run your application or my application it only shows most popular 20 movie that mean only fast page page:1.
I am searching how i can get page:2

**Comment by DmitryMalkovich** [comment]
@paveltech, sorry for delay!

From the movie database API:
http://docs.themoviedb.apiary.io/#reference/movies/movienowplaying/get?console=1

Optional Parameters (GET):
**page (Minimum 1, maximum 1000.)**

You have to change this file and use it respectively: "https://github.com/DmitryMalkovich/popular-movies-app/blob/master/app/src/main/java/com/dmitrymalkovich/android/popularmoviesapp/network/MovieDatabaseService.java"
